service: sls-base

plugins:
    - serverless-pseudo-parameters

provider:
    name: aws
    runtime: nodejs20.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: us-west-1
    iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionTable

resources:
    Resources:
        AuctionTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: AuctionTable
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH

functions:
    createAuction:
        handler: src/handlers/createAuction.handler
        events:
            - http:
                  method: POST
                  path: /auction
